//! Native cursor replacement for the undecorated window's resize border.
//!
//! `decorations: false` keeps an OS-managed resize band around the window. The
//! webview never receives mouse events there, so CSS/JS can't restyle it —
//! Windows paints its own resize cursors. We subclass the window procs and
//! intercept `WM_SETCURSOR` for the border hit-test codes
//! (`HTLEFT`..`HTBOTTOMRIGHT`), substituting the flame resize cursors embedded
//! via `include_bytes!`.
//!
//! TWO windows must be subclassed, because the band is split between them:
//! - the main window: its own `WM_NCHITTEST` (tao) returns `HTTOP` for the top
//!   few px of the client area;
//! - the `TAURI_DRAG_RESIZE_BORDERS` child that tauri-runtime-wry lays over the
//!   client area with a 4px frame-shaped region (`SetWindowRgn` cut-out). The
//!   outer 4px of the client area belongs to that child, so `WM_SETCURSOR` is
//!   delivered to *it*, not to the parent. Subclassing only the parent (the
//!   original mistake) left the whole band on stock Windows cursors.
//!
//! Notes on correctness:
//! - `WM_SETCURSOR`'s WPARAM packs the hit-test code in its LOWORD.
//! - Each subclass closure captures the previous window proc *before* replacing
//!   it (SetWindowLongPtrW returns the old value), so there is no recursion.
//! - Everything is best-effort: on any failure the stock Windows cursors stay.

#![cfg(windows)]

use std::sync::OnceLock;

/// Embedded .cur files (generated by tools/slice_cursors.py — re-run it after
/// editing the sprite sheet).
static CUR_DEFAULT: &[u8] = include_bytes!("../cursors/default.cur");
static CUR_GRAB: &[u8] = include_bytes!("../cursors/grab.cur");
static CUR_MOVE: &[u8] = include_bytes!("../cursors/move.cur");
static CUR_NS: &[u8] = include_bytes!("../cursors/ns-resize.cur");
static CUR_EW: &[u8] = include_bytes!("../cursors/ew-resize.cur");
static CUR_NWSE: &[u8] = include_bytes!("../cursors/nwse-resize.cur");
static CUR_NESW: &[u8] = include_bytes!("../cursors/nesw-resize.cur");

type HCURSOR = isize; // handles are pointer-sized; isize keeps the proc table simple
type HWND = isize;
type WPARAM = usize;
type LPARAM = isize;
type LRESULT = isize;

#[repr(C)]
struct POINT {
    x: i32,
    y: i32,
}

#[repr(C)]
struct RECT {
    left: i32,
    top: i32,
    right: i32,
    bottom: i32,
}

#[repr(C)]
struct MONITORINFO {
    cb_size: u32,
    rc_monitor: RECT,
    rc_work: RECT,
    dw_flags: u32,
}

#[repr(C)]
struct MINMAXINFO {
    pt_reserved: POINT,
    pt_max_size: POINT,
    pt_max_position: POINT,
    pt_min_track_size: POINT,
    pt_max_track_size: POINT,
}

#[link(name = "user32")]
unsafe extern "system" {
    fn LoadImageW(
        hinst: *mut core::ffi::c_void, name: *const u16, r#type: u32,
        cx: i32, cy: i32, fuse: u32,
    ) -> HCURSOR;
    fn SetCursor(hcursor: HCURSOR) -> HCURSOR;
    fn ShowWindow(hwnd: HWND, ncmdshow: i32) -> i32;
    fn IsZoomed(hwnd: HWND) -> i32;
    fn MonitorFromWindow(hwnd: HWND, flags: u32) -> isize;
    fn GetMonitorInfoW(hmonitor: isize, lpmi: *mut MONITORINFO) -> i32;
    fn EnumChildWindows(
        parent: HWND,
        lp_enum_func: unsafe extern "system" fn(HWND, LPARAM) -> i32,
        lparam: LPARAM,
    ) -> i32;
}

#[link(name = "comctl32")]
unsafe extern "system" {
    fn SetWindowSubclass(
        hwnd: HWND,
        pfnsubclass: unsafe extern "system" fn(HWND, u32, WPARAM, LPARAM, usize, usize) -> LRESULT,
        uidsubclass: usize,
        refdata: usize,
    ) -> i32;
    fn DefSubclassProc(
        hwnd: HWND,
        msg: u32,
        wparam: WPARAM,
        lparam: LPARAM,
    ) -> LRESULT;
}

const IMAGE_CURSOR: u32 = 2;
const LR_LOADFROMFILE: u32 = 0x0010;
const CURSOR_PX: i32 = 64; // every flame cursor PNG is 64x64
const WM_SETCURSOR: u32 = 0x0020;
const WM_GETMINMAXINFO: u32 = 0x0024;
const WM_NCLBUTTONDBLCLK: u32 = 0x00A3;
const SW_RESTORE: i32 = 9;
const SW_MAXIMIZE: i32 = 3;
const MONITOR_DEFAULTTONEAREST: u32 = 2;
const SUBCLASS_ID: usize = 0x444c50; // 'DLP'

// Hit-test codes from WM_NCHITTEST, delivered in WM_SETCURSOR's WPARAM LOWORD.
const HTCAPTION: i32 = 2;
const HTLEFT: i32 = 10;
const HTRIGHT: i32 = 11;
const HTTOP: i32 = 12;
const HTTOPLEFT: i32 = 13;
const HTTOPRIGHT: i32 = 14;
const HTBOTTOM: i32 = 15;
const HTBOTTOMLEFT: i32 = 16;
const HTBOTTOMRIGHT: i32 = 17;
const HTBORDER: i32 = 18;

struct Cursors {
    default: HCURSOR,
    #[allow(dead_code)]
    grab: HCURSOR,
    move_cur: HCURSOR,
    ns: HCURSOR,
    ew: HCURSOR,
    nwse: HCURSOR,
    nesw: HCURSOR,
}

static CURSORS: OnceLock<Cursors> = OnceLock::new();

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in bytes {
        h ^= b as u64;
        h = h.wrapping_mul(0x100000001b3);
    }
    h
}

fn load_cursor(bytes: &[u8]) -> Option<HCURSOR> {
    let path = std::env::temp_dir().join(format!("dlp-cursor-{:016x}.cur", fnv1a(bytes)));
    if !path.exists() {
        std::fs::write(&path, bytes).ok()?;
    }
    let wide: Vec<u16> = path.as_os_str().to_string_lossy().encode_utf16().chain([0]).collect();
    let h = unsafe {
        LoadImageW(
            std::ptr::null_mut(),
            wide.as_ptr(),
            IMAGE_CURSOR,
            CURSOR_PX,
            CURSOR_PX,
            LR_LOADFROMFILE,
        )
    };
    (h != 0).then_some(h)
}

fn init_cursors() -> Cursors {
    let load = |b: &[u8]| load_cursor(b).unwrap_or(0);
    Cursors {
        default: load(CUR_DEFAULT),
        grab: load(CUR_GRAB),
        move_cur: load(CUR_MOVE),
        ns: load(CUR_NS),
        ew: load(CUR_EW),
        nwse: load(CUR_NWSE),
        nesw: load(CUR_NESW),
    }
}

fn cursor_for_hit_test(ht: i32) -> HCURSOR {
    let cur = CURSORS.get_or_init(init_cursors);
    match ht {
        HTTOP | HTBOTTOM => cur.ns,
        HTLEFT | HTRIGHT => cur.ew,
        HTTOPLEFT | HTBOTTOMRIGHT => cur.nwse,
        HTTOPRIGHT | HTBOTTOMLEFT => cur.nesw,
        HTCAPTION => cur.move_cur,
        HTBORDER => cur.default,
        _ => 0,
    }
}

unsafe extern "system" fn flame_subclass_proc(
    hwnd: HWND,
    msg: u32,
    wparam: WPARAM,
    lparam: LPARAM,
    _uid: usize,
    _data: usize,
) -> LRESULT {
    if msg == WM_SETCURSOR {
        let ht = (lparam & 0xffff) as i16 as i32;
        let hcursor = cursor_for_hit_test(ht);
        if hcursor != 0 {
            SetCursor(hcursor);
            return 1;
        }
    } else if msg == WM_NCLBUTTONDBLCLK && (wparam as i32) == HTCAPTION {
        let zoomed = IsZoomed(hwnd);
        ShowWindow(hwnd, if zoomed != 0 { SW_RESTORE } else { SW_MAXIMIZE });
        return 0;
    }

    let res = DefSubclassProc(hwnd, msg, wparam, lparam);

    if msg == WM_GETMINMAXINFO {
        let hmon = MonitorFromWindow(hwnd, MONITOR_DEFAULTTONEAREST);
        if hmon != 0 {
            let mut mi = MONITORINFO {
                cb_size: std::mem::size_of::<MONITORINFO>() as u32,
                rc_monitor: RECT { left: 0, top: 0, right: 0, bottom: 0 },
                rc_work: RECT { left: 0, top: 0, right: 0, bottom: 0 },
                dw_flags: 0,
            };
            if GetMonitorInfoW(hmon, &mut mi) != 0 {
                let mmi = &mut *(lparam as *mut MINMAXINFO);
                mmi.pt_max_position.x = mi.rc_work.left - mi.rc_monitor.left;
                mmi.pt_max_position.y = mi.rc_work.top - mi.rc_monitor.top;
                mmi.pt_max_size.x = mi.rc_work.right - mi.rc_work.left;
                mmi.pt_max_size.y = mi.rc_work.bottom - mi.rc_work.top;
            }
        }
    }

    res
}

unsafe extern "system" fn enum_subclass_child(child: HWND, _lparam: LPARAM) -> i32 {
    SetWindowSubclass(child, flame_subclass_proc, SUBCLASS_ID, 0);
    1
}

pub fn install(window: &tauri::WebviewWindow) {
    if let Err(e) = install_impl(window) {
        eprintln!("[native_cursor] not installed: {e}");
    }
}

fn install_impl(window: &tauri::WebviewWindow) -> Result<(), String> {
    let hwnd = window.hwnd().map_err(|e| format!("no hwnd: {e}"))?.0 as HWND;

    unsafe {
        SetWindowSubclass(hwnd, flame_subclass_proc, SUBCLASS_ID, 0);
        EnumChildWindows(hwnd, enum_subclass_child, 0);
    }

    std::thread::spawn(move || {
        for _ in 0..20 {
            std::thread::sleep(std::time::Duration::from_millis(150));
            unsafe {
                EnumChildWindows(hwnd, enum_subclass_child, 0);
            }
        }
    });

    Ok(())
}
